import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  startDocSidebar: [
    {
      type: "category",
      label: "◉ 시작하기",
      collapsed: false,
      collapsible: true,
      items: [
        "started/getting-started/overview",
        "started/getting-started/set-dev-env-config",
        "started/getting-started/dev-convention",
        "started/getting-started/react-style-guide",
      ],
    },
    {
      type: "category",
      label: "◉ 참조",
      collapsed: false,
      collapsible: true,
      items: [
        "started/config-strategy/repository-config-strategy",
        "started/config-strategy/micro-frontend",
        "started/config-strategy/module-federation",
        "started/config-strategy/pnpm-turborepo",
      ],
    },
  ],
  documentDocSidebar: [
    {
      type: 'category',
      label: '◉ 개발 가이드',
      collapsed: false,
      collapsible: true,
      items: [
        "documents/dev/create-biz-pages",
        "documents/dev/navigating-pages",
        "documents/dev/use-rest-api",
        "documents/dev/update-data-with-rest-api",
        "documents/dev/using-ui-component",
        "documents/dev/create-domain-common-function",
        {
          type: 'category',
          label: '• Form 전송 방법',
          collapsed: true,
          collapsible: true,
          items: [
            'documents/index',
          ],
        },
        {
          type: 'category',
          label: '• Dialog 띄우기',
          collapsed: true,
          collapsible: true,
          items: [
            'documents/index',
          ],
        },
        'documents/index',
        'documents/index',
      ],
    },
  ],
  componentsDocSidebar: [
    'components/index',
  ],
  apiDocSidebar: [
    'apis/index',
  ],
  taskDocSidebar: [
    'task/intro',
    {
      type: 'category',
      label: '◉ Micro Frontend 준비',
      collapsed: true,
      collapsible: true,
      items: [
        'task/ready/set-mfe-proj/init-project-setup',
        'task/ready/set-mfe-proj/set-docusaurus-docs',
        'task/ready/set-mfe-proj/set-mfe-lib-shared',
        'task/ready/set-mfe-proj/set-mfe-app-main',
        'task/ready/set-mfe-proj/set-mfe-app-remote1',
        'task/ready/set-mfe-proj/npm-link',
      ],
    },
  ],
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
